name: my-smiski
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytorch>=2.2.0
  - torchvision>=0.17.0
  # - cudatoolkit=11.8 # remove if CPU-only
  - pip:
      - aiohttp>=3.9.0
      - requests>=2.31.0
      - Pillow>=10.0.0
      - pandas>=2.2.0
      - python-dotenv>=1.0.0
      - tqdm>=4.66.0
      - scikit-learn>=1.5.0
      - fastapi>=0.110.0
      - uvicorn[standard]>=0.29.0
